pipeline{
    agent any
    stages{
        stage("Hello"){
            steps{
                echo("Hello Pipeline")
            }
        }
    }
    
    post{
        always{
            echo "Running"
        }
        success{
            echo "Running success"
        }
        failure{
            echo "Running failure"
        }
        cleanup{
            echo "cleanup file"
        }
        
        
    }
}