pipeline{
    agent any
    triggers{
        pollSCM("*/1 * * * *")
        }
    stages{
        stage("Build"){
            steps{
                echo("Hello Pipeline")
            }
        }
        stage("Test"){
            steps{
                echo("Hello Test")
            }
        }
        stage("Deploy"){
            steps{
                echo("Hello Diploy")
            }
        }
    }
    
    post{
        always{
            echo "Running"
        }
        success{
            echo "Running success"
        }
        failure{
            echo "Running failure"

        }
        cleanup{
            echo "cleanup file"
        }
        
        
    }
}